#!/usr/bin/env python3
"""Generate user-facing service packs for domain routing and Mihomo.

A service pack is a deterministic combination of the official service domains
already defined in config/services.json. It deliberately does not turn DNS
answers into IP ownership data: service domains are the routing source here.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SERVICES = ROOT / "config" / "services.json"
PACKS = ROOT / "config" / "service_packs.json"
DEFAULT_OUTPUT = ROOT / "data" / "service-packs"


def load_config(path: Path) -> dict:
    data = json.loads(path.read_text(encoding="utf-8"))
    if data.get("schema_version") != 1:
        raise ValueError("unsupported service_packs schema_version")
    packs = data.get("packs")
    if not isinstance(packs, dict) or not packs:
        raise ValueError("service_packs.packs must be a non-empty object")
    services = json.loads(SERVICES.read_text(encoding="utf-8")).get("services", {})
    if not isinstance(services, dict) or not services:
        raise ValueError("services.json contains no services")

    for name, pack in packs.items():
        if not name or not isinstance(name, str):
            raise ValueError("pack name must be a non-empty string")
        selected = pack.get("services")
        if not isinstance(selected, list) or not selected:
            raise ValueError(f"{name}: services must be a non-empty list")
        if len(selected) != len(set(selected)):
            raise ValueError(f"{name}: duplicate service")
        unknown = sorted(set(selected) - set(services))
        if unknown:
            raise ValueError(f"{name}: unknown services: {unknown}")
    return data


def build_domains(pack: dict, services: dict) -> list[str]:
    domains = set()
    for service_name in pack["services"]:
        domains.update(services[service_name]["domains"])
    return sorted(domains)


def render_classical_yaml(domains: list[str]) -> str:
    lines = [
        "# Generated by CDN-Cloud-MagiTrickle.",
        "# Mihomo rule-provider: behavior=classical, format=yaml.",
        "payload:",
    ]
    lines.extend(f"  - 'DOMAIN-SUFFIX,{domain}'" for domain in domains)
    return "\n".join(lines) + "\n"


def render_mihomo_snippet(pack_name: str) -> str:
    url_base = (
        "https://raw.githubusercontent.com/avgustvishne/"
        "CDN-Cloud-MagiTrickle/main/data/service-packs"
    )
    file_name = f"{pack_name}-mihomo.yaml"
    return (
        f"# Add this provider under rule-providers in mihomo.yaml.\n"
        f"{pack_name}:\n"
        f"  type: http\n"
        f"  behavior: classical\n"
        f"  format: yaml\n"
        f"  interval: 43200\n"
        f"  url: {url_base}/{file_name}\n"
    )


def generate(config: dict, output: Path) -> list[Path]:
    services = json.loads(SERVICES.read_text(encoding="utf-8"))["services"]
    output.mkdir(parents=True, exist_ok=True)
    generated: list[Path] = []
    for name in sorted(config["packs"]):
        domains = build_domains(config["packs"][name], services)
        if not domains:
            raise ValueError(f"{name}: resolved service pack is empty")
        domain_path = output / f"{name}-domains.txt"
        yaml_path = output / f"{name}-mihomo.yaml"
        snippet_path = output / f"{name}-rule-provider.yaml"
        domain_path.write_text("\n".join(domains) + "\n", encoding="utf-8")
        yaml_path.write_text(render_classical_yaml(domains), encoding="utf-8")
        snippet_path.write_text(render_mihomo_snippet(name), encoding="utf-8")
        generated.extend((domain_path, yaml_path, snippet_path))
    return generated


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", default=str(PACKS))
    parser.add_argument("--services", default=str(SERVICES))
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT))
    args = parser.parse_args()

    global SERVICES
    SERVICES = Path(args.services)
    config = load_config(Path(args.config))
    generated = generate(config, Path(args.output))
    print(f"Generated {len(generated)} service-pack files.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
